# Default colors
[colors.primary]
background = '#1D1F28'
foreground = '#FDFDFD'

# Normal colors
[colors.normal]
# Bright colors
black   = '#282A36'
red     = '#F37F97'
green   = '#5ADECD'
yellow  = '#F2A272'
blue    = '#8897F4'
magenta = '#C574DD'
cyan    = '#79E6F3'
white   = '#FDFDFD'

[colors.bright]
black   = '#414458'
red     = '#FF4971'
green   = '#18E3C8'
yellow  = '#EBCB8B'
blue    = '#FF8037'
magenta = '#556FFF'
cyan    = '#3FDCEE'
white   = '#BEBEC1'

[font]
size = 8

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

